### ISSUE TITLE
Second Main window updates its position following first window

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-efx/efxclipse-rt#372]
If you clone the first window and add the copy as a second window to the application, dragging one window updates the position of the other, so they are "bound" to each other. See attached reproducer.

**Comment by JonasHelming** [comment]
[NewWindowBug.zip](https://github.com/eclipse-efx/efxclipse-rt/files/3496955/NewWindowBug.zip)

**Comment by tomsontom** [comment]
So the first finding is that it must have something to do with the cloneing because if you create a secondary window with
```java
MTrimmedWindow newWindow = modelService.createModelElement(MTrimmedWindow.class);
		newWindow.setX(100);
		newWindow.setY(100);
		newWindow.setWidth(500);
		newWindow.setHeight(500);
```

all is fine.

**Comment by tomsontom** [comment]
so the looking at `ModelServiceImpl#cloneElement()` I don't think efxclipse can do anything to fix the problem because there a Deep-Clone is done but nobody bothers to clear the transientData-Map which think is not correct and i case of efxclipse it causes the 2 elements getting handled by the same IEclipseContext instance.

So the things to do:
* file a bug against upstream starting a discussion if it is really appropriate to NOT clear the transient-data-Map
* until then you need to clean up the complete clone:
 * clearing up `transientData`-Maps
 * calling `MUIElement#setWidget(null)` on all MUIElements in the clone
